### ISSUE TITLE
UnityChanのライセンスについて

### ISSUE THREAD

**Issue by KyoheiTanamura** [kamanii24/AssetBundleManager#2]
『<a href="http://unity-chan.com/contents/guideline/" target="_blank">キャラクター利用のガイドライン</a>』
　弊社キャラクターのデジタルアセットデータを再配布する場合
『<a href="http://unity-chan.com/contents/faq/" target="_blank">キャラクター利用のガイドライン（FAQ）</a>』
　Github等のホスティングサービスで、自作のプロジェクトと一緒に『ユニティちゃん』のデジタルアセットを再配布したいと考えています。注意すべきことはありますか？

を確認した限りですと、
ライセンスドキュメント一式をリポジトリに含めたほうが宜しいのではないでしょうか？

**Comment by kamanii24** [comment]
失礼いたしました、ライセンスドキュメント一式入れ込みました。
ご指摘いただきありがとうございます。
